"""Add Users roles

Revision ID: a858e825a68f
Revises: 8e1753bea677
Create Date: 2023-11-10 22:44:46.946241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a858e825a68f"
down_revision: Union[str, None] = "8e1753bea677"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE role AS ENUM('admin', 'moderator', 'user')")
    op.add_column(
        "users",
        sa.Column(
            "roles",
            sa.Enum("admin", "moderator", "user", name="role"),
            nullable=True,
            default="user",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE role")
    op.drop_column("users", "roles")
    # ### end Alembic commands ###
